### ISSUE TITLE
Test on my own images

### ISSUE THREAD

**Issue by smahajan07** [twtygqyy/pytorch-LapSRN#1]
Hi, The code cannot take a random .jpg file as input and only a .mat file.
Is there any way to test the model on a random image?

**Comment by twtygqyy** [comment]
@smahajan07 You can load a jpg image and convert into numpy array, the rest thing will be same as current testing script. The reason why I used mat file is because the algorithm can achieve best performance with matlab bi-cubic function. Please refer https://github.com/twtygqyy/pytorch-vdsr/blob/master/test.py for testing with image files.

**Comment by smahajan07** [comment]
I have made some change in the repo to load the jpg file, but getting an error:

Traceback (most recent call last):
  File "/home/gabbar/Sarthak/pytorch-LapSRN/test.py", line 55, in <module>
    HR_2x, HR_4x = model(im_input)
  File "/home/gabbar/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gabbar/Sarthak/pytorch-LapSRN/lapsrn.py", line 85, in forward
    out = self.relu(self.conv_input(x))
  File "/home/gabbar/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gabbar/.local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/gabbar/.local/lib/python2.7/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_BAD_PARAM

I have the following [commit](https://github.com/smahajan07/pytorch-LapSRN/commit/4b3c3c51790c90e09a20fd6a45b2288c4bc2e03c). Please suggest any changes.

**Comment by twtygqyy** [comment]
@smahajan07 im_gt_y means the intensity channel of original image, I think you should write the code like this `np.array(Image.open("Set5/" + opt.image + ".jpg").convert('L'))`

**Comment by smahajan07** [comment]
Thanks! That worked.

But I seem to have no improvement in the image. I am using a low res upscaled image as input instead of bi cubic interpolation on a GT. Will that affect the result? I have uploaded the [results](https://github.com/smahajan07/pytorch-LapSRN/tree/master/results) for your reference. 

I have posted my actual problem on [here](https://www.reddit.com/r/deeplearning/comments/6gdyam/super_resolution_best_implementation_anyone/). Any help will be appreciated.

**Comment by twtygqyy** [comment]
@smahajan07 "I am using a low res upscaled image as input instead of bi cubic interpolation on a GT. Will that affect the result?"
That's correct! The model was trained on bicubiced images processed with Matlab function. You can also test with Image.BICUBIC function, which can give you obvious improvement. However, the PSNR performance will not be as good as using Matlab.

**Comment by smahajan07** [comment]
I used the Image.BICUBIC , but the [result](https://github.com/smahajan07/pytorch-LapSRN/blob/master/results/result_3.png) is the same, no improvement. Could you have a look at the [test.py](https://github.com/smahajan07/pytorch-LapSRN/blob/master/test.py#L47) and see if I am doing something wrong? I haven't changed it much though.

**Comment by twtygqyy** [comment]
@smahajan07  looked at your result images, it seems that you used bicubic interpolation while keep the size of the original image. While according to the LapSRN, you should down-sample the image with a factor of 4, and the output image will be the same size as your ground truth image, please check the difference between im_gt_y(**gt**), im_l_y (**4x smaller, input for model**), and im_b_y(**upsampled from im_l_y, same size of gt**)

**Comment by smahajan07** [comment]
Thanks, It works now! I just wanted ti test the model, will start training on my own data set to improve results if possible.
![finalresult1](https://user-images.githubusercontent.com/28476862/27166929-8b7c47d8-51bb-11e7-9dde-d1e4094c57d9.png)
![finalresult2](https://user-images.githubusercontent.com/28476862/27166944-a1076c2c-51bb-11e7-9544-ef9e99f49ea4.png)

**Comment by twtygqyy** [comment]
@smahajan07 Great! Let me know if you find something interesting!
