### ISSUE TITLE
training analysis 

### ISSUE THREAD

**Issue by MohamedBakrAli** [twtygqyy/pytorch-LapSRN#15]
Hi ,
I would like to ask you about the training time period and the Specifications of the machine that your train your model in ?

**Comment by twtygqyy** [comment]
Hi, @MohamedBakrAli I remember it took me about 20 hours to train for 100 epochs on a single GTX 1080Ti GPU.

**Comment by MohamedBakrAli** [comment]
thank you @twtygqyy.
You help me very much with answer my question.
