### ISSUE TITLE
could you provide the .h5 generated file?

### ISSUE THREAD

**Issue by ppannattee** [twtygqyy/pytorch-LapSRN#21]
I don't have environment good enoght to generate data with MATLAB.
could you provide the whole patches on T91 and BSDS200 datasets in format .hi5 file generated from 'generate_train_lap_pry.m' ?
thank you

**Comment by Siamw** [comment]
maybe it is too big to upload

**Comment by twtygqyy** [comment]
@thxkew Sry, Siamw is correct, those h5s are too large to be uploaded.
